### ISSUE TITLE
v -lib translated p_enemy.v launch an "array.vh" doesn't exist" error

### ISSUE THREAD

**Issue by beyondma** [vlang/doom#4]
when I run 'v -lib translated p_enemy.v' to make a v lib,it returned " Building module p_enemy.v...
Cross compiling /home/machao//.vlang//vlib//p_enemy.v.o
V panic: "/home/machao//.vlang//vlib/builtin/array.vh" doesn't exist"
how can I resolve it?

**Comment by nedpals** [comment]
Hello, what version of V are you running on?
